let nome = "Henrique Pereira de Souza";
let email = "hrpsouza@outlook.com";
let profissao = "Bancário";
let idade = 50;
let destino = "NY";
console.log("nome: " + nome);
console.log("email: " + email);
console.log("Profissão: " + profissao);
console.log("idade: " + idade);
console.log("destino: " + destino);
console.log(" testando passar as 4 informações através de 1 única linha de código: ");
console.log(" nome: " + nome, '\n', "email: " + email , '\n', "Profissão: " + profissao , '\n', "idade: " + idade , '\n',  "destino: " + destino );
console.log(" transmitindo a frase própria da tarefa do dia: ");
console.log("Olá," + nome + "! Somos aqui da agência de turismo Viagem dos Sonhos. Estamos te escrevendo este email, pois acabamos de confirmar as compras das passagens aéreas para " + destino + ". Confirma pra gente alguns dados? A sua idade é " + idade + ", você é " + profissao + " e o seu email é " + email + "? Ficamos no aguardo. Muito obrigado e boa viagem! :D");